# This is a basic workflow to help you get started with Actions

name: TEST1_get_s3 list

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get-s3-list:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [metaloid]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ALEX_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ALEX_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.METALOID_AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
         # role-session-name: MySessionTEST1
      - run: |
          aws s3 ls --profile metaloid

      # Runs a set of commands using the runners shell
      ##- name: Run a multi-line script
      ##  run: |
      ##    echo Add other actions to build,
      ##    echo test, and deploy your project.
